services:
  - type: web
    name: deepfake-voice-detection-api
    runtime: python
    buildCommand: pip install -r requirements.txt && chmod +x startup.sh
    startCommand: ./startup.sh
    plan: free
    envVars:
      - key: API_KEY
        value: deepfake_detection_api_key_2026
      - key: PYTHON_VERSION
        value: 3.12.0
