services:
  - type: web
    name: deepfake-voice-detection-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python download_model.py && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 1
    plan: free
    envVars:
      - key: API_KEY
        value: deepfake_detection_api_key_2026
      - key: PYTHON_VERSION
        value: 3.12.0
